import { Router } from 'express';
import timeOffCategories from './timeOffCategories';
import timeOffStatusesRouter from './timeOffStatuses';
import timeOffsRouter from './timeOffs';
import countriesRouter from './countries';
import regionsRouter from './regions';
import timeOffCategoriesXCountryRouter from './timeOffCategoriesXCountry';
import teamMembersRouter from './teamMembers';
import teamMemberProjectsRouter from './teamMemberProjects';
import projectsRouter from './projects';
import rolesRouter from './roles';
import usersRouter from './users';
import rbacPermissionsRouter from './rbacPermissions';
import rbacRolesRouter from './rbacRoles';
import rbacUserRolesRouter from './rbacUserRoles';
import rbacOptionsRouter from './rbacOptions';
import rbacAuthUsersRouter from './rbacAuthUsers';
import supervisorAssignmentsRouter from './supervisorAssignments';
import holidaysRouter from './holidays';
import timeOffHolidaysRouter from './timeOffHolidays';
import chartsRouter from './charts';
import notificationsRouter from './notifications';
import endorsementsRouter from './endorsements';
import hiringRouter from './hiring';
import bonusCategoriesRouter from './bonusCategories';
import endorsementBonusesRouter from './endorsementBonuses';
import tierBandsRouter from './tierBands';
import bonusSubcategoriesRouter from './bonusSubcategories';
import timeoffChangeLogRouter from './reports/timeoffChangeLog';
import upcomingVacationRouter from './reports/upcomingVacation';
import workdayReconciliationRouter from './reports/workdayReconciliation';
import dynamicReportsRouter from './reports/dynamicReports';
import clientsRouter from './clients';
import clientContactsRouter from './clientContacts';
import workdayInfoRouter from './workdayInfo';
import functionalAreasRouter from './functionalArea';
import holidaySwapRouter from './holidaySwap.routes';
import holidaySwapExceptionRouter from './holidaySwapException.routes';
import pendingRequestsRouter from './pendingRequests.routes';
import benchRouter from './bench.routes';
import persistenceTemplateRouter from './persistenceTemplate.routes';
import persistenceDataTypeRouter from './persistenceDataType.routes';
import persistenceTableRouter from './persistenceTable.routes';
import persistenceJobRouter from './persistenceJob.routes';
import shiftRouter from './shift.routes';
import timeoffPeriodMaintenanceRouter from './timeoff-period-maintenance.routes';
import compensatoryTimeRouter from './compensatoryTime.routes';
import workflowTemplatesRouter from '../services/workflow/routes/templates';
import workflowInstancesRouter from '../services/workflow/routes/instances';
import workflowTasksRouter from '../services/workflow/routes/tasks';
import workflowAdminRouter from '../services/workflow/routes/admin';
import dashboardRouter from './dashboard.routes';
import emailTestRouter from './email-test.routes';
import standaloneTasksRouter from '../services/standalone-tasks/routes/tasks';
import standaloneTaskCommentsRouter from '../services/standalone-tasks/routes/comments';
import apiKeysAdminRouter from '../services/api-keys/routes/admin';
import teamMemberBonusRouter from './teamMemberBonus';
import aiInsightsRouter from '../services/aiInsights/routes';
import uploadsRouter from './uploads';
import tpCyclesRouter from './topPerformers/cycles';
import tpNominationsRouter from './topPerformers/nominations';
import tpAnonymizationRouter from './topPerformers/anonymization';
import tpVotingRouter from './topPerformers/voting';
import tpResultsRouter from './topPerformers/results';
import giftCardPoolsRouter from '../services/giftcards/catalogs/pools/pools.routes';
import giftCardReasonsRouter from '../services/giftcards/catalogs/reasons/reasons.routes';
import giftCardTypesRouter from '../services/giftcards/catalogs/cardTypes/cardTypes.routes';
import giftCardValuesRouter from '../services/giftcards/catalogs/cardValues/cardValues.routes';

export default function registerRoutes() {
  const router = Router();

  router.use('/time-off-category', timeOffCategories);
  router.use('/time-off-statuses', timeOffStatusesRouter);
  router.use('/time-offs', timeOffsRouter);
  router.use('/countries', countriesRouter);
  router.use('/regions', regionsRouter);
  router.use('/time-off-categories-by-country', timeOffCategoriesXCountryRouter);
  router.use('/team-members', teamMembersRouter);
  router.use('/team-member-projects', teamMemberProjectsRouter);
  router.use('/projects', projectsRouter);
  router.use('/positions', rolesRouter);
  router.use('/users', usersRouter);
  router.use('/rbac/permissions', rbacPermissionsRouter);
  router.use('/rbac/roles', rbacRolesRouter);
  router.use('/rbac/user-roles', rbacUserRolesRouter);
  router.use('/rbac/options', rbacOptionsRouter);
  router.use('/rbac/auth-users', rbacAuthUsersRouter);
  router.use('/supervisor-assignments', supervisorAssignmentsRouter);
  router.use('/holidays', holidaysRouter);
  router.use('/time-off-holidays', timeOffHolidaysRouter);
  router.use('/charts', chartsRouter);
  router.use('/notifications', notificationsRouter);
  router.use('/endorsements', endorsementsRouter);
  router.use('/hiring', hiringRouter);
  router.use('/bonus-categories', bonusCategoriesRouter);
  router.use('/endorsement-bonuses', endorsementBonusesRouter);
  router.use('/tier-bands', tierBandsRouter);
  router.use('/bonus-subcategories', bonusSubcategoriesRouter);
  router.use('/reports/time-off/change-log', timeoffChangeLogRouter);
  router.use('/reports/time-off/upcoming-vacation', upcomingVacationRouter);
  router.use('/reports/time-off/workday-reconciliation', workdayReconciliationRouter);
  router.use('/reports/dynamic', dynamicReportsRouter);
  router.use('/clients', clientsRouter);
  router.use('/client-contacts', clientContactsRouter);
  router.use('/workday-info', workdayInfoRouter);
  router.use('/functional-areas', functionalAreasRouter);
  router.use('/holiday-swaps', holidaySwapRouter);
  router.use('/holiday-swaps', holidaySwapExceptionRouter);
  router.use('/team/pending-requests', pendingRequestsRouter);
  router.use('/bench-move', benchRouter);
  router.use('/persistence-template', persistenceTemplateRouter);
  router.use('/persistence-data-type', persistenceDataTypeRouter);
  router.use('/persistence-table', persistenceTableRouter);
  router.use('/persistence-job', persistenceJobRouter);
  router.use('/shift', shiftRouter);
  router.use('/timeoff-period-maintenance', timeoffPeriodMaintenanceRouter);
  router.use('/compensatory-time', compensatoryTimeRouter);
  router.use('/workflow/templates', workflowTemplatesRouter);
  router.use('/workflow/instances', workflowInstancesRouter);
  router.use('/workflow', workflowTasksRouter);
  router.use('/workflow', workflowAdminRouter);
  router.use('/dashboard', dashboardRouter);
  router.use('/email-test', emailTestRouter);
  router.use('/standalone-tasks', standaloneTasksRouter);
  router.use('/standalone-tasks', standaloneTaskCommentsRouter);
  router.use('/admin/api-keys', apiKeysAdminRouter);
  router.use('/team-member-bonuses', teamMemberBonusRouter);
  router.use('/ai', aiInsightsRouter);
  router.use('/uploads', uploadsRouter);
  router.use('/top-performers/cycles', tpCyclesRouter);
  router.use('/top-performers/nominations', tpNominationsRouter);
  router.use('/top-performers/anonymization', tpAnonymizationRouter);
  router.use('/top-performers/voting', tpVotingRouter);
  router.use('/top-performers/results', tpResultsRouter);
  router.use('/giftcards/catalogs/pools', giftCardPoolsRouter);
  router.use('/giftcards/catalogs/reasons', giftCardReasonsRouter);
  router.use('/giftcards/catalogs/card-types', giftCardTypesRouter);
  router.use('/giftcards/catalogs/card-values', giftCardValuesRouter);

  return router;
}
