import { Router } from 'express';
import timeOffCategories from './timeOffCategories';
import timeOffStatusesRouter from './timeOffStatuses';
import timeOffsRouter from './timeOffs';
import countriesRouter from './countries';
import regionsRouter from './regions';
import timeOffCategoriesXCountryRouter from './timeOffCategoriesXCountry';
import teamMembersRouter from './teamMembers';
import teamMemberProjectsRouter from './teamMemberProjects';
import projectsRouter from './projects';
import rolesRouter from './roles';
import usersRouter from './users';
import rbacPermissionsRouter from './rbacPermissions';
import rbacRolesRouter from './rbacRoles';
import rbacUserRolesRouter from './rbacUserRoles';
import rbacOptionsRouter from './rbacOptions';
import supervisorAssignmentsRouter from './supervisorAssignments';
import holidaysRouter from './holidays';
import timeOffHolidaysRouter from './timeOffHolidays';
import chartsRouter from './charts';
import notificationsRouter from './notifications';
import endorsementsRouter from './endorsements';
import hiringRouter from './hiring';
import bonusCategoriesRouter from './bonusCategories';
import endorsementBonusesRouter from './endorsementBonuses';
import tierBandsRouter from './tierBands';
import bonusSubcategoriesRouter from './bonusSubcategories';
import timeoffChangeLogRouter from './reports/timeoffChangeLog';
import dynamicReportsRouter from './reports/dynamicReports';
import clientsRouter from './clients';
import workdayInfoRouter from './workdayInfo';
import functionalAreasRouter from './functionalArea';

export default function registerRoutes() {
  const router = Router();

  router.use('/time-off-category', timeOffCategories);
  router.use('/time-off-statuses', timeOffStatusesRouter);
  router.use('/time-offs', timeOffsRouter);
  router.use('/countries', countriesRouter);
  router.use('/regions', regionsRouter);
  router.use('/time-off-categories-by-country', timeOffCategoriesXCountryRouter);
  router.use('/team-members', teamMembersRouter);
  router.use('/team-member-projects', teamMemberProjectsRouter);
  router.use('/projects', projectsRouter);
  router.use('/roles', rolesRouter);
  router.use('/users', usersRouter);
  router.use('/rbac/permissions', rbacPermissionsRouter);
  router.use('/rbac/roles', rbacRolesRouter);
  router.use('/rbac/user-roles', rbacUserRolesRouter);
  router.use('/rbac/options', rbacOptionsRouter);
  router.use('/supervisor-assignments', supervisorAssignmentsRouter);
  router.use('/holidays', holidaysRouter);
  router.use('/time-off-holidays', timeOffHolidaysRouter);
  router.use('/charts', chartsRouter);
  router.use('/notifications', notificationsRouter);
  router.use('/endorsements', endorsementsRouter);
  router.use('/hiring', hiringRouter);
  router.use('/bonus-categories', bonusCategoriesRouter);
  router.use('/endorsement-bonuses', endorsementBonusesRouter);
  router.use('/tier-bands', tierBandsRouter);
  router.use('/bonus-subcategories', bonusSubcategoriesRouter);
  router.use('/reports/time-off/change-log', timeoffChangeLogRouter);
  router.use('/reports/dynamic', dynamicReportsRouter);
  router.use('/clients', clientsRouter);
  router.use('/workday-info', workdayInfoRouter);
  router.use('/functional-areas', functionalAreasRouter);

  return router;
}
