import { Router } from 'express';
import timeOffCategories from './timeOffCategories';
import timeOffStatusesRouter from './timeOffStatuses';
import timeOffsRouter from './timeOffs';
import countriesRouter from './countries';
import regionsRouter from './regions';
import timeOffCategoriesXCountryRouter from './timeOffCategoriesXCountry';
import teamMembersRouter from './teamMembers';
import teamMemberProjectsRouter from './teamMemberProjects';
import projectsRouter from './projects';
import rolesRouter from './roles';
import usersRouter from './users';
import rbacPermissionsRouter from './rbacPermissions';
import rbacRolesRouter from './rbacRoles';
import rbacUserRolesRouter from './rbacUserRoles';
import rbacOptionsRouter from './rbacOptions';
import rbacAuthUsersRouter from './rbacAuthUsers';
import supervisorAssignmentsRouter from './supervisorAssignments';
import supervisorCoverageRouter from './supervisorCoverage';
import authorizerAssignmentsRouter from './authorizerAssignments';
import holidaysRouter from './holidays';
import timeOffHolidaysRouter from './timeOffHolidays';
import chartsRouter from './charts';
import notificationsRouter from './notifications';
import endorsementsRouter from './endorsements';
import hiringRouter from './hiring';
import bonusCategoriesRouter from './bonusCategories';
import incomeTypesRouter from './incomeTypes';
import otherIncomesRouter from './otherIncomes';
import endorsementBonusesRouter from './endorsementBonuses';
import tierBandsRouter from './tierBands';
import bonusSubcategoriesRouter from './bonusSubcategories';
import timeoffChangeLogRouter from './reports/timeoffChangeLog';
import upcomingVacationRouter from './reports/upcomingVacation';
import workdayReconciliationRouter from './reports/workdayReconciliation';
import gtVacationUnderFiveDaysRouter from './reports/gtVacationUnderFiveDays';
import dynamicReportsRouter from './reports/dynamicReports';
import performanceCaseReportsRouter from './reports/performanceCases';
import clientsRouter from './clients';
import clientContactsRouter from './clientContacts';
import workdayInfoRouter from './workdayInfo';
import functionalAreasRouter from './functionalArea';
import flagTypeActionsRouter from './flagTypeActions';
import holidaySwapRouter from './holidaySwap.routes';
import holidaySwapExceptionRouter from './holidaySwapException.routes';
import pendingRequestsRouter from './pendingRequests.routes';
import benchRouter from './bench.routes';
import persistenceTemplateRouter from './persistenceTemplate.routes';
import persistenceDataTypeRouter from './persistenceDataType.routes';
import persistenceTableRouter from './persistenceTable.routes';
import persistenceJobRouter from './persistenceJob.routes';
import shiftRouter from './shift.routes';
import timeoffPeriodMaintenanceRouter from './timeoff-period-maintenance.routes';
import compensatoryTimeRouter from './compensatoryTime.routes';
import workflowTemplatesRouter from '../services/workflow/routes/templates';
import workflowInstancesRouter from '../services/workflow/routes/instances';
import workflowTasksRouter from '../services/workflow/routes/tasks';
import workflowAdminRouter from '../services/workflow/routes/admin';
import workflowUsersRouter from '../services/workflow/routes/users';
import dashboardRouter from './dashboard.routes';
import timeOffHubRouter from './timeOffHub.routes';
import emailTestRouter from './email-test.routes';
import emailStatisticsRouter from './email-statistics.routes';
import emailMessageInsightsRouter from './email-message-insights.routes';
import standaloneTasksRouter from '../services/standalone-tasks/routes/tasks';
import mondayConnectionsRouter from '../services/monday-integration/routes/mondayConnections';
import standaloneTaskCommentsRouter from '../services/standalone-tasks/routes/comments';
import flagIntakeRouter from '../services/flag-intake/routes/flagIntake';
import recurringTaskTemplatesRouter from '../services/recurring-task-templates/routes/templates';
import apiKeysAdminRouter from '../services/api-keys/routes/admin';
import teamMemberBonusRouter from './teamMemberBonus';
import teamMemberReimbursementRouter from './teamMemberReimbursement';
import teamMemberOncallRouter from './teamMemberOncall';
import aiInsightsRouter from '../services/aiInsights/routes';
import sopRouter from './sop.routes';
import uploadsRouter from './uploads';
import tpCyclesRouter from './topPerformers/cycles';
import tpNominationsRouter from './topPerformers/nominations';
import tpAnonymizationRouter from './topPerformers/anonymization';
import tpVotingRouter from './topPerformers/voting';
import tpResultsRouter from './topPerformers/results';
import giftCardPoolsRouter from '../services/giftcards/catalogs/pools/pools.routes';
import giftCardReasonsRouter from '../services/giftcards/catalogs/reasons/reasons.routes';
import giftCardTypesRouter from '../services/giftcards/catalogs/cardTypes/cardTypes.routes';
import giftCardValuesRouter from '../services/giftcards/catalogs/cardValues/cardValues.routes';
import phoneContractsRouter from './phoneContracts.routes';
import phoneContractsExternalRouter from './phoneContractsExternal.routes';
import laptopInventoryRouter from './laptopInventory.routes';
import payrolRouter from './payrol.routes';
import bonusImpactRouter from './bonusImpact.routes';
import giftCardAssignmentsRouter from '../services/giftcards/assignments/assignments.routes';
import giftCardDocumentationRouter from '../services/giftcards/documentation/documentation.routes';
import sopLibraryRouter from './sopLibrary.routes';
import { storedProcedureRoutes } from './storedProcedures';
import { storedProcedureOrchestrator } from '../services/storedProcedures/StoredProcedureOrchestrator';
import fieldglassSowsRouter from './fieldglassSow.routes';
import externalBonusIntakeRouter from './externalBonusIntake.routes';
import performanceCasesRouter from '../services/performance-cases/routes/cases';
import findingsRouter from './findings.routes';

export default function registerRoutes() {
  const router = Router();

  router.use('/time-off-category', timeOffCategories);
  router.use('/time-off-statuses', timeOffStatusesRouter);
  router.use('/time-offs', timeOffsRouter);
  router.use('/countries', countriesRouter);
  router.use('/regions', regionsRouter);
  router.use('/time-off-categories-by-country', timeOffCategoriesXCountryRouter);
  router.use('/team-members', teamMembersRouter);
  router.use('/team-member-projects', teamMemberProjectsRouter);
  router.use('/projects', projectsRouter);
  router.use('/positions', rolesRouter);
  router.use('/users', usersRouter);
  router.use('/rbac/permissions', rbacPermissionsRouter);
  router.use('/rbac/roles', rbacRolesRouter);
  router.use('/rbac/user-roles', rbacUserRolesRouter);
  router.use('/rbac/options', rbacOptionsRouter);
  router.use('/rbac/auth-users', rbacAuthUsersRouter);
  router.use('/supervisor-assignments', supervisorAssignmentsRouter);
  router.use('/supervisor-coverage', supervisorCoverageRouter);
  router.use('/authorizer-assignments', authorizerAssignmentsRouter);
  router.use('/holidays', holidaysRouter);
  router.use('/time-off-holidays', timeOffHolidaysRouter);
  router.use('/charts', chartsRouter);
  router.use('/notifications', notificationsRouter);
  router.use('/endorsements', endorsementsRouter);
  router.use('/hiring', hiringRouter);
  router.use('/bonus-categories', bonusCategoriesRouter);
  router.use('/income-types', incomeTypesRouter);
  router.use('/other-incomes', otherIncomesRouter);
  router.use('/endorsement-bonuses', endorsementBonusesRouter);
  router.use('/tier-bands', tierBandsRouter);
  router.use('/bonus-subcategories', bonusSubcategoriesRouter);
  router.use('/reports/time-off/change-log', timeoffChangeLogRouter);
  router.use('/reports/time-off/upcoming-vacation', upcomingVacationRouter);
  router.use('/reports/time-off/workday-reconciliation', workdayReconciliationRouter);
  router.use('/reports/time-off/gt-vacation-under-five-days', gtVacationUnderFiveDaysRouter);
  router.use('/reports/dynamic', dynamicReportsRouter);
  router.use('/reports/performance-cases', performanceCaseReportsRouter);
  router.use('/clients', clientsRouter);
  router.use('/client-contacts', clientContactsRouter);
  router.use('/workday-info', workdayInfoRouter);
  router.use('/functional-areas', functionalAreasRouter);
  router.use('/flag-type-actions', flagTypeActionsRouter);
  router.use('/holiday-swaps', holidaySwapRouter);
  router.use('/holiday-swaps', holidaySwapExceptionRouter);
  router.use('/team/pending-requests', pendingRequestsRouter);
  router.use('/bench-move', benchRouter);
  router.use('/persistence-template', persistenceTemplateRouter);
  router.use('/persistence-data-type', persistenceDataTypeRouter);
  router.use('/persistence-table', persistenceTableRouter);
  router.use('/persistence-job', persistenceJobRouter);
  router.use('/shift', shiftRouter);
  router.use('/timeoff-period-maintenance', timeoffPeriodMaintenanceRouter);
  router.use('/compensatory-time', compensatoryTimeRouter);
  router.use('/phone-contracts', phoneContractsRouter);
  router.use('/phone-contracts/external', phoneContractsExternalRouter);
  router.use('/laptops', laptopInventoryRouter);
  router.use('/payrol', payrolRouter);
  router.use('/bonus-impacts', bonusImpactRouter);
  router.use('/workflow/templates', workflowTemplatesRouter);
  router.use('/workflow/instances', workflowInstancesRouter);
  router.use('/workflow', workflowTasksRouter);
  router.use('/workflow', workflowAdminRouter);
  router.use('/workflow/users', workflowUsersRouter);
  router.use('/dashboard', dashboardRouter);
  router.use('/time-off-hub', timeOffHubRouter);
  router.use('/email-test', emailTestRouter);
  router.use('/email-statistics', emailStatisticsRouter);
  router.use('/email-message-insights', emailMessageInsightsRouter);
  router.use('/standalone-tasks', standaloneTasksRouter);
  router.use('/monday-connections', mondayConnectionsRouter);
  router.use('/standalone-tasks', standaloneTaskCommentsRouter);
  router.use('/flag-intake', flagIntakeRouter);
  router.use('/recurring-task-templates', recurringTaskTemplatesRouter);
  router.use('/admin/api-keys', apiKeysAdminRouter);
  router.use('/team-member-bonuses', teamMemberBonusRouter);
  router.use('/team-member-reimbursements', teamMemberReimbursementRouter);
  router.use('/team-member-oncall', teamMemberOncallRouter);
  router.use('/ai', aiInsightsRouter);
  router.use('/sop', sopRouter);
  router.use('/uploads', uploadsRouter);
  router.use('/top-performers/cycles', tpCyclesRouter);
  router.use('/top-performers/nominations', tpNominationsRouter);
  router.use('/top-performers/anonymization', tpAnonymizationRouter);
  router.use('/top-performers/voting', tpVotingRouter);
  router.use('/top-performers/results', tpResultsRouter);
  router.use('/giftcards/catalogs/pools', giftCardPoolsRouter);
  router.use('/giftcards/catalogs/reasons', giftCardReasonsRouter);
  router.use('/giftcards/catalogs/card-types', giftCardTypesRouter);
  router.use('/giftcards/catalogs/card-values', giftCardValuesRouter);
  router.use('/giftcards/assignments', giftCardAssignmentsRouter);
  router.use('/giftcards/documentation', giftCardDocumentationRouter);
  router.use('/sop-library', sopLibraryRouter);
  router.use('/stored-procedures', storedProcedureRoutes(storedProcedureOrchestrator));
  router.use('/fieldglass-sows', fieldglassSowsRouter);
  router.use('/bonuses/external', externalBonusIntakeRouter);
  router.use('/performance-cases', performanceCasesRouter);
  router.use('/findings', findingsRouter);

  return router;
}
