import { prisma } from '../../db/prisma';
import { AppError } from '../../errors/AppError';
import { auditOrchestrator } from '../audit/AuditOrchestrator';
import { generateTriviaBatch } from './components/GenerateTriviaBatch';
import { dedupeAgainstExisting } from './components/DedupeQuestions';
import { selectDashboardQuestions } from './components/SelectDashboardQuestions';
import type { TriviaQuestionDTO, UpdateTriviaQuestionDTO } from '@shared/dto';

const REQUESTED_QUESTION_COUNT = 30;
const EXISTING_QUESTION_SAMPLE_SIZE = 150;

export async function pullNewBatch(createdBy: number, createdByEmail: string): Promise<{ batchId: number }> {
  const pending = await prisma.triviaBatch.findFirst({ where: { status: 'pending' } });
  if (pending) {
    throw new AppError('A trivia batch is already in progress', 409);
  }

  const batch = await prisma.triviaBatch.create({
    data: { status: 'pending', requestedQuestionCount: REQUESTED_QUESTION_COUNT, createdBy },
  });

  void runBatch(batch.id, createdBy, createdByEmail);

  return { batchId: batch.id };
}

async function runBatch(batchId: number, createdBy: number, createdByEmail: string): Promise<void> {
  try {
    const existingQuestions = await prisma.triviaQuestion.findMany({
      select: { questionText: true },
      take: EXISTING_QUESTION_SAMPLE_SIZE,
      orderBy: { createdAt: 'desc' },
    });

    const generated = await generateTriviaBatch(existingQuestions.map((q) => q.questionText));

    const allExisting = await prisma.triviaQuestion.findMany({ select: { questionHash: true } });
    const existingHashSet = new Set(allExisting.map((q) => q.questionHash));

    const deduped = dedupeAgainstExisting(generated, existingHashSet);

    for (const question of deduped) {
      const created = await prisma.triviaQuestion.create({
        data: {
          batchId,
          questionText: question.questionText,
          questionHash: question.questionHash,
          option1: question.option1,
          option2: question.option2,
          option3: question.option3,
          option4: question.option4,
          correctOptionIndex: question.correctOptionIndex,
          createdBy,
        },
      });

      await auditOrchestrator.log({
        entityName: 'trq_trivia_questions',
        entityId: String(created.id),
        createdBy: createdByEmail,
        oldValues: null,
        newValues: created as unknown as Record<string, unknown>,
        comment: `Trivia question generated by batch ${batchId}`,
      });
    }

    await prisma.triviaBatch.update({
      where: { id: batchId },
      data: { status: 'completed', insertedQuestionCount: deduped.length, completedAt: new Date() },
    });
  } catch (err: unknown) {
    const message = err instanceof AppError ? err.message : 'Trivia batch generation failed unexpectedly';
    await prisma.triviaBatch.update({
      where: { id: batchId },
      data: { status: 'failed', errorMessage: message, completedAt: new Date() },
    });
  }
}

export async function getDashboardQuestions(teamMemberId: number): Promise<TriviaQuestionDTO[]> {
  const questions = await selectDashboardQuestions(teamMemberId);
  return questions.map((q) => ({
    id: q.id,
    question: q.questionText,
    options: [q.option1, q.option2, q.option3, q.option4],
    correctOptionIndex: q.correctOptionIndex,
  }));
}

export async function updateQuestion(
  id: number,
  input: UpdateTriviaQuestionDTO,
  _updatedBy: number,
  updatedByEmail: string,
) {
  const existing = await prisma.triviaQuestion.findUnique({ where: { id } });
  if (!existing) {
    throw new AppError('Trivia question not found', 404);
  }

  const updated = await prisma.triviaQuestion.update({
    where: { id },
    data: { ...(input.isActive !== undefined ? { isActive: input.isActive } : {}) },
  });

  await auditOrchestrator.log({
    entityName: 'trq_trivia_questions',
    entityId: String(id),
    createdBy: updatedByEmail,
    oldValues: existing as unknown as Record<string, unknown>,
    newValues: updated as unknown as Record<string, unknown>,
    comment: `Trivia question ${id} updated`,
  });

  return updated;
}

export async function deleteQuestion(id: number, deletedByEmail: string): Promise<void> {
  const existing = await prisma.triviaQuestion.findUnique({ where: { id } });
  if (!existing) {
    throw new AppError('Trivia question not found', 404);
  }

  await prisma.triviaQuestion.delete({ where: { id } });

  await auditOrchestrator.log({
    entityName: 'trq_trivia_questions',
    entityId: String(id),
    createdBy: deletedByEmail,
    oldValues: existing as unknown as Record<string, unknown>,
    newValues: null,
    comment: `Trivia question ${id} deleted`,
  });
}
