import { prisma } from '../../db/prisma';
import { AppError } from '../../errors/AppError';
import { auditOrchestrator } from '../audit/AuditOrchestrator';
import { generateTriviaBatch } from './components/GenerateTriviaBatch';
import { dedupeAgainstExisting } from './components/DedupeQuestions';

const REQUESTED_QUESTION_COUNT = 30;
const EXISTING_QUESTION_SAMPLE_SIZE = 150;

export async function pullNewBatch(createdBy: number, createdByEmail: string): Promise<{ batchId: number }> {
  const pending = await prisma.triviaBatch.findFirst({ where: { status: 'pending' } });
  if (pending) {
    throw new AppError('A trivia batch is already in progress', 409);
  }

  const batch = await prisma.triviaBatch.create({
    data: { status: 'pending', requestedQuestionCount: REQUESTED_QUESTION_COUNT, createdBy },
  });

  void runBatch(batch.id, createdBy, createdByEmail);

  return { batchId: batch.id };
}

async function runBatch(batchId: number, createdBy: number, createdByEmail: string): Promise<void> {
  try {
    const existingQuestions = await prisma.triviaQuestion.findMany({
      select: { questionText: true },
      take: EXISTING_QUESTION_SAMPLE_SIZE,
      orderBy: { createdAt: 'desc' },
    });

    const generated = await generateTriviaBatch(existingQuestions.map((q) => q.questionText));

    const allExisting = await prisma.triviaQuestion.findMany({ select: { questionHash: true } });
    const existingHashSet = new Set(allExisting.map((q) => q.questionHash));

    const deduped = dedupeAgainstExisting(generated, existingHashSet);

    for (const question of deduped) {
      const created = await prisma.triviaQuestion.create({
        data: {
          batchId,
          questionText: question.questionText,
          questionHash: question.questionHash,
          option1: question.option1,
          option2: question.option2,
          option3: question.option3,
          option4: question.option4,
          correctOptionIndex: question.correctOptionIndex,
          createdBy,
        },
      });

      await auditOrchestrator.log({
        entityName: 'trq_trivia_questions',
        entityId: String(created.id),
        createdBy: createdByEmail,
        oldValues: null,
        newValues: created as unknown as Record<string, unknown>,
        comment: `Trivia question generated by batch ${batchId}`,
      });
    }

    await prisma.triviaBatch.update({
      where: { id: batchId },
      data: { status: 'completed', insertedQuestionCount: deduped.length, completedAt: new Date() },
    });
  } catch (err: unknown) {
    const message = err instanceof AppError ? err.message : 'Trivia batch generation failed unexpectedly';
    await prisma.triviaBatch.update({
      where: { id: batchId },
      data: { status: 'failed', errorMessage: message, completedAt: new Date() },
    });
  }
}
