import { HubConfig } from './hub.types';

export const maintenanceHubConfig: HubConfig = {
  key: 'maintenance',
  title: 'Maintenance',
  subtitle: 'Manage master data tables used across the application.',
  buttons: [
    {
      title: 'Bonus Categories',
      description: 'Create and manage bonus category definitions.',
      path: '/maintenance/bonus-categories',
      permission: 'BonusCategories',
    },
    {
      title: 'Bonus Subcategories',
      description: 'Manage subcategories within each bonus category.',
      path: '/maintenance/bonus-subcategories',
      permission: 'BonusCategories',
    },
    {
      title: 'Countries',
      description: 'Configure country records used across the system.',
      path: '/maintenance/countries',
      permission: 'Countries',
    },
    {
      title: 'Flag Type Actions',
      description: 'Manage the action link shown on each weekly flag category.',
      path: '/maintenance/flag-type-actions',
      permission: 'FlagTypeActions',
    },
    {
      title: 'Functional Areas',
      description: 'Define functional areas for team organization.',
      path: '/maintenance/functional-areas',
      permission: 'FunctionalAreas',
    },
    {
      title: 'Holidays',
      description: 'Manage public holidays by country and year.',
      path: '/maintenance/holidays',
      permission: 'Holidays',
    },
    {
      title: 'Projects',
      description: 'View and manage project records.',
      path: '/maintenance/projects',
      permission: 'Projects',
    },
    {
      title: 'Regions',
      description: 'Create and manage region definitions used to group countries.',
      path: '/maintenance/regions',
      permission: 'Regions',
    },
    {
      title: 'Supervisor Assignments',
      description: 'Assign and review supervisor relationships.',
      path: '/maintenance/supervisor-assignments',
      permission: 'SupervisorAssignments',
    },
    {
      title: 'Supervisor Coverage',
      description: 'Manage temporary coverage arrangements between supervisors.',
      path: '/maintenance/supervisor-coverage',
      permission: 'SupervisorCoverage',
    },
    {
      title: 'Team Members',
      description: 'Manage team member profiles and settings.',
      path: '/maintenance/team-members',
      permission: 'TeamMembers',
    },
    {
      title: 'Tier Bands',
      description: 'Configure compensation tier band definitions.',
      path: '/maintenance/tier-bands',
      permission: 'TierBands',
    },
    {
      title: 'Time Off Statuses',
      description: 'Manage the statuses used in time off workflows.',
      path: '/maintenance/time-off-statuses',
      permission: 'TimeOffStatuses',
    },
    {
      title: 'Type of Time Off',
      description: 'Define time off categories available to employees.',
      path: '/maintenance/time-off-types',
      permission: 'TimeOffCategories',
    },
    {
      title: 'Type of Time Off by Country',
      description: 'Assign time off types to specific countries.',
      path: '/maintenance/category-country',
      permission: 'TimeOffCategoriesByCountry',
    },
    {
      title: 'Users',
      description: 'Manage application user accounts and access.',
      path: '/maintenance/users',
      permission: 'Users',
    },
    {
      title: 'Workday Info',
      description: 'Configure workday calendars and schedule data.',
      path: '/maintenance/workday-info',
      permission: 'WorkdayInfo',
    },
    {
      title: 'Shifts',
      description: 'Define and manage reusable shift templates (start/end times, weekly hours) that can be assigned to team members.',
      path: '/maintenance/shifts',
      permission: 'Shift',
    },
    {
      title: 'Gift Card Pools',
      description: 'Manage cost-center pools for gift card distribution.',
      path: '/maintenance/gift-cards/pools',
      permission: 'GiftCardCatalog',
    },
    {
      title: 'Gift Card Reasons',
      description: 'Define reasons available for gift card distribution requests.',
      path: '/maintenance/gift-cards/reasons',
      permission: 'GiftCardCatalog',
    },
    {
      title: 'Gift Card Types',
      description: 'Configure the types of gift cards available in the catalog.',
      path: '/maintenance/gift-cards/card-types',
      permission: 'GiftCardCatalog',
    },
    {
      title: 'Gift Card Values',
      description: 'Set the denominations and currencies for each card type.',
      path: '/maintenance/gift-cards/card-values',
      permission: 'GiftCardCatalog',
    },
    {
      title: 'Gift Card Inventory',
      description: 'Upload gift card inventory CSV files into the staging table.',
      path: '/maintenance/gift-cards/inventory',
      permission: 'GiftCardCatalog',
    },
    {
      title: 'Gift Card Distribution Requests',
      description: 'Request and review gift card distribution assignments.',
      path: '/maintenance/gift-cards/request',
      permission: 'GiftCardAssignment',
    },
    {
      title: 'Gift Card Documentation',
      description: 'Record and review gift card usage receipts and proof of spend.',
      path: '/maintenance/gift-cards/documentation',
      permission: 'GiftCardDocumentation',
    },
    {
      title: 'Knowledge Base',
      description: 'Upload and manage SOP documents for the AI knowledge base.',
      path: '/maintenance/knowledge-base',
      permission: 'SopKnowledge',
    },
    {
      title: 'SOP Library',
      description: 'Manage SOP library entries and control tier-based access.',
      path: '/admin/sop-library',
      permission: 'SopLibrary',
    },
    {
      title: 'API Permission Catalog',
      description: 'Manage the resource/action pairs that can be granted to external API keys.',
      path: '/maintenance/permission-catalog',
      permission: 'RBACApiKeys',
    },
    {
      title: 'Reports',
      description: 'Access Maintenance and data quality reports.',
      path: '/reports?module=maintenance',
    },
    {
      title: 'Send Test Email',
      description: 'Send test emails via SES in all supported configurations.',
      path: '/maintenance/email-test',
      permission: 'EmailAdmin',
    },
    {
      title: 'Email Send Statistics',
      description: 'View rolling SES sending activity, bounces, complaints, and quota.',
      path: '/maintenance/email-statistics',
      permission: 'EmailAdmin',
    },
    {
      title: 'Email Delivery Status',
      description: 'Look up the delivery outcome of a specific email by MessageId.',
      path: '/maintenance/email-message-insights',
      permission: 'EmailAdmin',
    },
    {
      title: 'Findings',
      description: 'Monitor changes detected in watched fields across projects.',
      path: '/maintenance/findings',
      permission: 'Findings',
    },
    {
      title: 'Object & Field Manager',
      description: 'Configure which entities and fields change detection watches.',
      path: '/maintenance/watched-fields',
      permission: 'WatchedFields',
    },
  ],
};
